version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: score_mvp
      MYSQL_USER: score_mvp
      MYSQL_PASSWORD: score_mvp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://score_mvp:score_mvp@db:3306/score_mvp
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=http://localhost:3000
      - ENVIRONMENT=development
    volumes:
      - .:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data: 