version: '3.8'

services:
  db:
    image: postgres:15
    container_name: scoremvp-db
    restart: always
    environment:
      POSTGRES_DB: scoremvp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://score_mvp:score_mvp@db:3306/score_mvp
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=http://localhost:3000
      - ENVIRONMENT=development
    volumes:
      - .:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata: 