[deploy]
# escolha ON_FAILURE, ALWAYS ou NEVER (tudo em maiúsculas)
restartPolicyType     = "ON_FAILURE"
restartPolicyMaxRetries = 5    # opcional
healthcheckPath       = "/"
healthcheckTimeout    = 60
startCommand          = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
