[deploy]
# escolha ON_FAILURE, ALWAYS ou NEVER (tudo em maiúsculas)
restartPolicyType     = "ON_FAILURE"
restartPolicyMaxRetries = 5    # opcional
healthcheckPath       = "/"
healthcheckTimeout    = 60
startCommand          = "node index.js"
